version: "3.4"
services:
  eng-software:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    depends_on:
      - postgres
    environment:
      PYTHONPATH: grader
      PYTHONUNBUFFERED: 1
      DB_URL: postgresql://user:password@postgres/dbgestaodeconhecimento
      LOGLEVEL: INFO
    networks:
      - eng-software-rede
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn eng_software_projeto.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000

  eng-software-nginx:
    image: nginx:latest
    container_name: eng-software-nginx
    restart: always
    networks:
      - eng-software-rede
    links:
    - eng-software-front
    volumes:
    - ./eng_software_projeto-frontend:/www
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  eng-software-front:
    image: php:7.3-fpm
    container_name: eng-software-front-php-fpm
    networks:
      - eng-software-rede
    environment:
      BACKEND_ADDRESS: eng-software
      BACKEND_PORT: 8000
    depends_on:
      - postgres
      - eng-software
    volumes:
    - ./eng_software_projeto-frontend:/www

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
      - ./database:/database
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - eng-software-rede

networks:
  eng-software-rede:
    driver: bridge
