version: "3.4"
services:
  eng-sofware:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      PYTHONPATH: grader
      PYTHONUNBUFFERED: 1
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - eng-sofware-rede
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn eng_software_projeto.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000

  eng-sofware-nginx:
    image: nginx:latest
    container_name: eng-sofware-nginx
    restart: always
    ports:
    - "80:80"
    links:
    - eng-sofware-front
    volumes:
    - ./eng_software_projeto-frontend:/www
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  eng-sofware-front:
    image: php:7.3-fpm
    container_name: eng-sofware-front-php-fpm
    volumes:
    - ./eng_software_projeto-frontend:/www

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
      - ./database:/database
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - eng-sofware-rede

networks:
  eng-sofware-rede:
    driver: bridge
